### ISSUE TITLE
[1.7.10] Client side only, please mark as such

### ISSUE THREAD

**Issue by dries007** [lumien231/Custom-Main-Menu#108]
Please mark this mod as a client side mod in your manifest, so we don't have to start up server 7 times to weed out all client mods.
Just add "ModSide: CLIENT" to the manifest via gradle:
Place 
```
manifest {
    attributes 'ModSide': 'CLIENT'
}
```
inside the jar block.
Thanks.

**Comment by lumien231** [comment]
In 1.9 it is marked as clientsideonly, 1.7.10 is not getting updates anymore & this is not a huge issue.

**Comment by xLink** [comment]
@lumien231 can you please get the 1.7.10 the update? most of the mods that are worth using are stuck on 1.7.10 and without this since update we cannot use your mod in any older packs as the server keeps breaking with it in there.

The tekkit packs use the same set of jars on the client as on the server which is where the issue lies, but can be ultimately fixed in a few minutes by you.
