### ISSUE TITLE
How to get transparent boxes

### ISSUE THREAD

**Issue by Biofusionz** [lumien231/Custom-Main-Menu#29]
How do I make the blacktransparent.png file? I've tried changing the transparency levels for it but whatever I do it's just solid black

**Comment by lumien231** [comment]
It's just a sem transparent black image.

**Comment by Biofusionz** [comment]
Thanks for the quick reply. The image I am using is semi transparent. I've even tried getting one off of google images with no luck. Any chance you'd be able to upload one? I've been trying for an hour trying to get it to work

**Comment by Flenix** [comment]
I can second this. BioFusionz seemed to give up on the idea of using semi transparent images so I'm giving it a shot.

Using this image: http://silvania.co.uk/brushedlogo.png for example, in any image editor the shadow and glow and semi transparent and will show things through. Within the mod, however, it's solid: http://ctrlv.in/530247

I noticed a note on the page; "Some of these examples might not work / look properly with the latest CMM version due to changes in the format". Could this be related?

**Comment by lumien231** [comment]
Might have messed up the blending in the recent versions, will look into this.

**Comment by lumien231** [comment]
Huh, that's odd, for me the image you posted works fine. Could you post your whole json (and ressources if you have any) ?

**Comment by Biofusionz** [comment]
Sorry for the long delay.

Here's the resources, https://www.dropbox.com/s/543yqcc78oncel4/CMM%20resources.zip?dl=0
And here's the json, http://pastebin.com/viGvR1EU
