### ISSUE TITLE
Hotbar bug

### ISSUE THREAD

**Issue by jakmanda05** [lumien231/Custom-Main-Menu#324]
If I have this mod activated my hotbar in game looks like that
![2019-01-12_09 26 52](https://user-images.githubusercontent.com/46620756/51071112-528feb80-164c-11e9-8fc9-1e6847a0d8f9.png)

Please tell me how I can fix it.....

**Comment by zarzwour** [comment]
dont add it server side

**Comment by lumien231** [comment]
If you only have Custom Main Menu installed it looks like that?

**Comment by jakmanda05** [comment]
Yes

**Comment by Pantheonpvp** [comment]
up please i've the same and i've promised to my players an update between monday and thursday of the week !!

**Comment by Pantheonpvp** [comment]
please contact me when the bug has been resolved
by discord: Fire_Link#5066

**Comment by smmmadden** [comment]
Looks like an issue with another mod causing that.  I just installed (first time) SmoothFont 1.12.2-2.0-alpha-5 on my client machine, and was able to see my hotbar, menu and other screens change to a font I set it to (Arial).  I've been using CMM for almost 2 years.  Everything rendered fine.  

Since you never mentioned what version of the mods, server or client you are using it's impossible to know what you have setup that could be causing the issues.  Perhaps the below will help you based on what I've just tested this on, and/or you can look in your logfile to make sure there are no errors/exceptions when you start your server.  
Windows 10 Pro x64 - Server & Client
Forge Client: 1.12.2 - 2795
Forge Server: 1.12.2 - 2795
Custom Main Menu - 1.12.2-2.0.9
Resource Loader - 1.12.1 - 1.5.3
Custom Backgrounds 1.12 - 1.1.1
JEI 1.12.2 - 4.14.4.263
Hwyla 1.12.2 - 1.8.26-B41
