### ISSUE TITLE
Button WebText bug

### ISSUE THREAD

**Issue by MarkusOderSo** [lumien231/Custom-Main-Menu#419]
Hello,

i have a problem with displaying an external text (Webtext) in a button.

This is my JSON: https://hastebin.com/gidizibope.bash

And this is the result: https://share.jonasdev.de/xJr1377UhZ.png

**Comment by ROMVoid95** [comment]
that link brings up a very interesting site but no image. and the reason its not loading is due to the api your calling delivering the text page as 
`Content-Type: text/html; charset=UTF-8`. 
Where as im sure it needs to be 
`Content-Type: text/plain; charset=utf-8`

these are set in the return headers from the api so if they don't have a route or way to deliver this as plain text then your pretty much sol afaik

**Comment by MarkusOderSo** [comment]
Thanks for your help
