### ISSUE TITLE
Button Sounds Not Working

### ISSUE THREAD

**Issue by Hink1** [lumien231/Custom-Main-Menu#53]
My JSON File (mainmenu.JSON): http://pastebin.com/8Mp8szMN
All my sounds are in 'builder-tools[root folder]\resources\sounds'

All sound files are in the vorbis .OGG audio file format.

**Comment by lumien231** [comment]
Do you have Resource Loader installed?

**Comment by lumien231** [comment]
Also, please post the ogg file you are trying to use

**Comment by Ionaru** [comment]
Same issue here, using latest 1.7.10 versions of CustomMainMenu and ResourceLoader.
I am using an .ogg file copies from the legacy Minecraft sounds folder.

**Comment by lumien231** [comment]
Ok finally found a tutorial on how to add custom sounds: http://sethbling.com/customsound.
Download the Resource Pack from there and look at how it's done. Due to the nature of Resource Loader you don't have the assets folder so the folder structure would be "resources/minecraft/sounds/". You then use "minecraft:SOUNDNAME" as the name of the sound.
